spring:
  application:
    name: university
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dinugroza3@gmail.com
    password: pdrc wauh mlux dqwg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



jwt.secret: 470d677417ed8f552f69e14d363850291654e8484161fd171a37676e848f7ffb
jwt:
  expiration-time: 360000